prop.table(table(titanic$Survived))
titanic <- read.csv('/home/ubuntu/Desktop/train.csv',stringsAsFactors = FALSE)
table(titanic$Survived)
table(titanic$Pclass)
summary(titanic)
prop.table(table(titanic$Survived))
test$Survived <- rep(0, 418)
titanic
str(titanic)
submit <- data.frame(PassengerId=titanic$PassengerId, Survived=titanic$Survived)
summary(titanic$Sex)
install.packages("RColorBrewer")
library(RColorBrewer)
data("Titanic")
data(Titanic)
hist(titanic$Sex)
hist(titanic$Sex,breaks = 5)
barplot(titanic$Pclass)
prop.table(table(titanic$Sex,titanic$Survived))
prop.table(table(titanic$Sex,titanic$Survived),1)
prop.table(table(titanic$Sex,titanic$Survived),2)
summary(titanic$Age)
titanic$Child <- 0
titanic
titanic$Child
titanic$Child[titanic$Age < 18] <- 1
titanic$Age
titanic$Child
table(titanic$Child)
aggregate(titanic$Survived ~ titanic$Child + titanic$Sex, data = titanic, FUN = sum)
aggregate(titanic$Survived ~ titanic$Child + titanic$Sex, data = titanic, FUN = sum,FUN = ength)
aggregate(Survived ~ Child + Sex, data=titanic, FUN=function(x) {sum(x)/length(x)})
titanic$Fare
library(rpart)
fit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data = titanic, method = "class")
plot(fit)
text(fit)
fancyRpartPlot(fit)
installed.packages("fancyRPlot")
install.packages('rattle')
install.packages('rattle')
install.packages('rpart.plot')
install.packages('RColorBrewer')
install.packages("RColorBrewer")
library(rattle)
library(rpart.plot)
library(RColorBrewer)
fancyRpartPlot(fit)
installed.packages("fancyRPlot")
Prediction <- predict(fit, test, type = "class")
Prediction <- predict(fit, titanic, type = "class")
submit <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)
Prediction
submit <- data.frame(PassengerId = titanic$PassengerId, Survived = Prediction)
submit
u = table(titanic$Pclass,titanic$Survived)
u
plot(u)
barplot(u)
barplot(titanic$Survived)
barplot(titanic$Sex)
barplot(u)
install.packages('ggplot')
install.packages('ggplot2')
install.packages("ggplot2")
barplot(u,col = 'green')
colors = c('orange','green')
barplot(u,col = colors)
colors = c('orange','green','red')
barplot(u,col = colors)
barplot(u,col = colors,main = 'PCLASS AND SURVIVED',ylab = 'PCLASS')
barplot(u,col = colors,main = 'PCLASS AND SURVIVED',ylab = 'PCLASS',xlab = 'SURVIVED')
barplot(u,col = colors,main = 'PCLASS AND SURVIVED',ylab = 'PCLASS',xlab = 'SURVIVED',beside = TRUE)
barplot(u,col = colors,main = 'PCLASS AND SURVIVED',ylab = 'PCLASS',xlab = 'SURVIVED')
barplot(u,col = colors,main = 'PCLASS AND SURVIVED',ylab = 'PCLASS',xlab = 'SURVIVED',beside = TRUE)
